"""This script evaluates the performance of a simple CNN model on the MNIST dataset using three different training sets:
1. Imbalanced training set (original MNIST training set)
2. Local DeepSMOTE training set (generated by the local client)
3. FedDeepSMOTE training set (generated by the federated learning process)
"""



import os
import json
import math
import random
import numpy as np
from collections import Counter

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import TensorDataset, DataLoader

from torchvision.datasets import MNIST
from torchvision import transforms


# =========================
# CONFIG
# =========================
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
SEED = 42

EPOCHS = 5
BATCH_SIZE = 128
LR = 1e-3

# Train sets (txt) – DeepSMOTE format
IMB_IMG = "./MNIST/trn_img/0_trn_img.txt"
IMB_LAB = "./MNIST/trn_lab/0_trn_lab.txt"

LOCAL_IMG = "./MNIST/trn_img_local/0_trn_img.txt"
LOCAL_LAB = "./MNIST/trn_lab_local/0_trn_lab.txt"

FED_IMG = "./MNIST/trn_img_f/0_trn_img.txt"
FED_LAB = "./MNIST/trn_lab_f/0_trn_lab.txt"

# Output
OUT_DIR = "./results_eval"
OUT_JSON = os.path.join(OUT_DIR, "mnist_eval_results.json")


# =========================
# Reproducibility
# =========================
def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


# =========================
# Simple CNN (stable baseline)
# =========================
class SimpleCNN(nn.Module):
    def __init__(self, num_classes=10):
        super().__init__()
        self.conv1 = nn.Conv2d(1, 32, 3, padding=1)
        self.conv2 = nn.Conv2d(32, 64, 3, padding=1)
        self.pool = nn.MaxPool2d(2, 2)
        self.fc1 = nn.Linear(64 * 7 * 7, 128)
        self.fc2 = nn.Linear(128, num_classes)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))   # 28->14
        x = self.pool(F.relu(self.conv2(x)))   # 14->7
        x = x.view(x.size(0), -1)
        x = F.relu(self.fc1(x))
        return self.fc2(x)


# =========================
# Data loading helpers
# =========================
def load_deepsmote_txt(img_path: str, lab_path: str):
    if not os.path.isfile(img_path) or not os.path.isfile(lab_path):
        raise FileNotFoundError(f"Missing:\n{img_path}\n{lab_path}")

    X = np.loadtxt(img_path).astype(np.float32)  # (N,784), values in [-1,1]
    y = np.loadtxt(lab_path).astype(np.int64)    # (N,)
    X = X.reshape(-1, 1, 28, 28)
    return X, y


def make_train_loader(img_path: str, lab_path: str):
    X, y = load_deepsmote_txt(img_path, lab_path)
    print(f"Train set: {img_path} -> X={X.shape}, y={y.shape}, counts={Counter(y)}")

    X_t = torch.tensor(X, dtype=torch.float32)
    y_t = torch.tensor(y, dtype=torch.long)

    ds = TensorDataset(X_t, y_t)
    return DataLoader(ds, batch_size=BATCH_SIZE, shuffle=True, num_workers=0)


def make_test_loader():
    # MNIST test set in [0,1] -> transform to [-1,1] for consistency with DeepSMOTE data
    tfm = transforms.Compose([
        transforms.ToTensor(),                  # [0,1]
        transforms.Lambda(lambda x: x * 2 - 1)   # [-1,1]
    ])
    test_ds = MNIST(root="./mnist_raw", train=False, download=True, transform=tfm)
    return DataLoader(test_ds, batch_size=256, shuffle=False, num_workers=0)


# =========================
# Metrics
# =========================
def confusion_matrix(y_true, y_pred, num_classes=10):
    cm = np.zeros((num_classes, num_classes), dtype=np.int64)
    for t, p in zip(y_true, y_pred):
        cm[t, p] += 1
    return cm


def macro_f1(cm):
    f1s = []
    for c in range(cm.shape[0]):
        tp = cm[c, c]
        fp = cm[:, c].sum() - tp
        fn = cm[c, :].sum() - tp
        denom = (2 * tp + fp + fn)
        f1 = 0.0 if denom == 0 else (2 * tp) / denom
        f1s.append(f1)
    return float(np.mean(f1s))


def acsa(cm):
    # Average per-class accuracy (recall per class)
    accs = []
    for c in range(cm.shape[0]):
        denom = cm[c, :].sum()
        accs.append(0.0 if denom == 0 else cm[c, c] / denom)
    return float(np.mean(accs))


def gmean(cm):
    # Geometric mean of per-class recall
    recalls = []
    for c in range(cm.shape[0]):
        denom = cm[c, :].sum()
        recalls.append(1e-12 if denom == 0 else cm[c, c] / denom)
    # geometric mean
    prod = 1.0
    for r in recalls:
        prod *= r
    return float(prod ** (1.0 / len(recalls)))


# =========================
# Train + Evaluate
# =========================
def train_model(train_loader):
    model = SimpleCNN().to(DEVICE)
    opt = torch.optim.Adam(model.parameters(), lr=LR)
    crit = nn.CrossEntropyLoss()

    model.train()
    for ep in range(1, EPOCHS + 1):
        running = 0.0
        for xb, yb in train_loader:
            xb, yb = xb.to(DEVICE), yb.to(DEVICE)
            opt.zero_grad()
            logits = model(xb)
            loss = crit(logits, yb)
            loss.backward()
            opt.step()
            running += loss.item() * xb.size(0)

        print(f"Epoch {ep}/{EPOCHS} loss={running/len(train_loader.dataset):.4f}")
    return model


@torch.no_grad()
def evaluate_model(model, test_loader):
    model.eval()
    y_true = []
    y_pred = []

    for xb, yb in test_loader:
        xb = xb.to(DEVICE)
        logits = model(xb)
        pred = torch.argmax(logits, dim=1).cpu().numpy()
        y_pred.extend(pred.tolist())
        y_true.extend(yb.numpy().tolist())

    y_true = np.array(y_true, dtype=np.int64)
    y_pred = np.array(y_pred, dtype=np.int64)
    cm = confusion_matrix(y_true, y_pred, num_classes=10)

    return {
        "MacroF1": macro_f1(cm),
        "GMean": gmean(cm),
        "ACSA": acsa(cm),
        "ConfusionMatrix": cm.tolist()
    }


def run_one_case(name, img_path, lab_path, test_loader):
    print(f"\n=== {name} ===")
    train_loader = make_train_loader(img_path, lab_path)
    model = train_model(train_loader)
    metrics = evaluate_model(model, test_loader)
    print(f"{name} -> MacroF1: {metrics['MacroF1']:.6f}  GM: {metrics['GMean']:.6f}  ACSA: {metrics['ACSA']:.6f}")
    return metrics


def main():
    set_seed(SEED)
    os.makedirs(OUT_DIR, exist_ok=True)

    test_loader = make_test_loader()

    results = {}
    results["Imbalanced"] = run_one_case("Train on Imbalanced", IMB_IMG, IMB_LAB, test_loader)
    results["LocalDeepSMOTE"] = run_one_case("Train on Local DeepSMOTE", LOCAL_IMG, LOCAL_LAB, test_loader)
    results["FedDeepSMOTE"] = run_one_case("Train on FedDeepSMOTE", FED_IMG, FED_LAB, test_loader)

    with open(OUT_JSON, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2)

    print(f"\nSaved results -> {os.path.abspath(OUT_JSON)}")


if __name__ == "__main__":
    main()
